// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBPYjDs1OFabV2ohweCSuzi0QQFnUt0luc',
    appId: '1:422184868306:web:790eeacf0593706d09500b',
    messagingSenderId: '422184868306',
    projectId: 'akademi-mobil-a3fe6',
    authDomain: 'akademi-mobil-a3fe6.firebaseapp.com',
    storageBucket: 'akademi-mobil-a3fe6.appspot.com',
    measurementId: 'G-GJ074CRZD9',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDP8jbGUThJheW3qTePICZDuKKK9mNE-fg',
    appId: '1:422184868306:android:29d1a465cb6dc14c09500b',
    messagingSenderId: '422184868306',
    projectId: 'akademi-mobil-a3fe6',
    storageBucket: 'akademi-mobil-a3fe6.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCIqyBYY4OZpyqsVBEC4xMtgMZYAvSlbac',
    appId: '1:422184868306:ios:f9cd90ae635d77c809500b',
    messagingSenderId: '422184868306',
    projectId: 'akademi-mobil-a3fe6',
    storageBucket: 'akademi-mobil-a3fe6.appspot.com',
    iosClientId: '422184868306-2cs41f7a1k1jt82438ujjcqblqgfv1p6.apps.googleusercontent.com',
    iosBundleId: 'com.example.akademiMobil',
  );
}
